server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    password: sa
    username: sa
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
